DOMAIN = "electricity_price"
NAME = "total_electricity_price"
ENTITY_ID = "sensor.total_electricity_price"

CONF_ELOVERBLIK_TOKEN = "eloverblik_token"
CONF_METERING_POINT = "metering_point"
CONF_PRICE_SENSOR = "price_sensor"

ATTR_TODAY = "today"
ATTR_TOMORROW = "tomorrow"
ATTR_TOTAL_TODAY = "total_today"
ATTR_TOTAL_TOMORROW = "total_tomorrow"
ATTR_CURRENCY = "currency"
ATTR_COUNTRY = "country"
ATTR_REGION = "region"
ATTR_CURRENT_PRICE = "current_price"
ATTR_CURRENT_RAW_PRICE = "current_raw_price"
ATTR_CURRENT_TRANSPORT_FEES = "current_transport_fees"
ATTR_CURRENT_TAX = "current_tax"
ATTR_CURRENT_ELECTRICITY_FEE = "current_electricity_fee"
ATTR_STATE_CLASS = "state_class"
ATTR_LAST_UPDATED = "last_updated"
ATTR_ALL_TARIFS = "tarifs"
ATTR_TRANS_NETTARIF = "transmissions_nettarif"
ATTR_SYSTEMTARIF = "systemtarif"
ATTR_ELAFGIFT = "elafgift"
ATTR_HOUR_NETTARIF = "nettarif_c_time"